version: "3.2"
services:
  opcserver:
    container_name: opcserver
    image: ghcr.io/mstoffel-sag/opc-ua-demo-server:latest
    restart: always
    ports:
      - "4840:4840"
    networks:
      backend:
networks:
  backend:
    name: opc-ua-gateway_backend
